Change url project's website
mate-desktop/mate-user-guide pull request #36
Opened 2019-06-09 21:29 UTC by tamplan

Now the official web site is https://mate-desktop.org/.

2019-06-10 15:50 UTC, raveit65 approved these changes
LGTM,
thanks.

2019-06-10 17:17 UTC, selectiveduplicate requested changes
The change I think wasn't necessary, since the website by default always uses https and the www part doesn't matter.
Besides that, everything seems fine 🙂 , except the following lines in ``gostools.xml`` and ``mate-user-guide.pot``, they should be changed to:

```
Prefix the web page address with https://, as in https://mate-desktop.org.
```

instead of 

```
Prefix the web page address with http://, as in https://mate-desktop.org.
```

2019-06-11 13:44 UTC, rbuj commented on mate-user-guide/C/gostools.xml
> +      If you enter a web page address, your default web browser will open the page. Prefix the web page address with http://, as in https://mate-desktop.org.
URL prefix should be the same.
```
... address with https://, as in https://mate-desktop.org.
```

2019-06-11 13:44 UTC, rbuj commented on mate-user-guide/mate-user-guide.pot
> +msgid "If you enter only the location of a file, an appropriate application will launch to open it. If you enter a web page address, your default web browser will open the page. Prefix the web page a
URL prefix should be the same.
```
... address with https://, as in https://mate-desktop.org.
```

2019-06-16 17:27 UTC, raveit65 commented
@tamplan 
Can please follow suggestions for this PR?
So, that we can finish this.
...before opening a bunch of new ones.

Thanks

2019-06-16 17:43 UTC, tamplan commented
Ok, i read and modify the files.

2019-06-16 17:49 UTC, tamplan commented
Done.

2019-06-16 18:05 UTC, raveit65 commented
Thanks for update, i will squash both commits into one :)

2019-06-16 18:10 UTC, raveit65 commented
Oh sorry, i just did it locally and merge it 
https://github.com/mate-desktop/mate-user-guide/commit/7ac840ab3a8f7c0cae66784305242db0b5793fea
But good to know that you are familiar with the rebase command now ;)
Thank you.

2019-06-16 18:10 UTC, closed without merging

2019-06-16 18:31 UTC, tamplan commented
> Thanks for update, i will squash both commits into one :)

Tanks for squashing :)